In [ ]:
import sys
import pandas as pd
from src.staging import staging_fies, staging_inep
from src.transform_layer_1 import transform_inscritos, transform_ofertas, transform_inep, verificar_colunas_inep
from src.transform_layer_2 import tratar_nans_cine_inscritos, tratar_nans_cine_ofertas
from src.trasnform_layer_3 import processar_modalidades_e_peneira
from src.load import load_inscritos,load_ofertas,auditoria_inscritos_carregados,auditoria_ofertas_carregadas,exportar_para_sqlite
    
comando = 'transform'
etapa = '3'

# --- CAMADA: STAGING ---
if comando == "staging":
    staging_fies()
    staging_inep()

# --- CAMADA: TRANSFORM ---
elif comando == "transform":

    if etapa == "1":
        transform_inep()
    elif etapa == "2":
        transform_inscritos()
    elif etapa == "3":
        transform_ofertas()
    elif etapa == "4":
        verificar_colunas_inep()
    elif etapa == "5":
        tratar_nans_cine_inscritos()
    elif etapa == "6":
        tratar_nans_cine_ofertas()
    elif etapa == "7":
        processar_modalidades_e_peneira()
    elif etapa == "all":
        transform_inep()
        transform_inscritos()
        transform_ofertas()
        verificar_colunas_inep()
        tratar_nans_cine_inscritos()
        tratar_nans_cine_ofertas()
        processar_modalidades_e_peneira()

elif comando == "load":

    load_inscritos()
    load_ofertas()
    auditoria_inscritos_carregados()
    auditoria_ofertas_carregadas()
    exportar_para_sqlite()

==================================================
Iniciando Transformação e Unificação: FIES Ofertas
==================================================
Buscando arquivos em: /home/eq_lucas/Documents/projetos/kdd-pipeline-microdata-fies/data/02_staging/microdata fies
  [*] Lendo e padronizando: fies_1_ofertas_2021_sem_duplicata.csv
  [*] Lendo e padronizando: fies_2_ofertas_2019_sem_duplicata.csv
  [*] Lendo e padronizando: fies_1_ofertas_2020_sem_duplicata.csv
  [*] Lendo e padronizando: fies_1_ofertas_2019_sem_duplicata.csv
  [*] Lendo e padronizando: fies_2_ofertas_2021_sem_duplicata.csv
  [*] Lendo e padronizando: fies_2_ofertas_2020_sem_duplicata.csv

[*] Empilhando todos os semestres num único Dataset...
[*] Ordenando o Dataset por Ano e Semestre...

[*] Iniciando Merge com o Dataset Mestre do INEP (Áreas CINE)...
  -> Merge concluído com sucesso! Colunas do INEP adicionadas.

--- Processo Concluído! ---
Total de 6 arquivos unificados e enriquecidos.
Checkpoint salvo em: /home/eq_lucas/Documents/projetos/kdd-pipeline-microdata-fies/data/03_transform/fies/fies_ofertas_unificado.parquet
Total de linhasx colunas no dataset final: (143623, 69)

==================================================
🔍 INICIANDO VALIDAÇÃO DE QUALIDADE: OFERTAS
==================================================

⏳ Carregando dados da camada 01_RAW...

⏳ Carregando dados da camada 02_STAGING...

----------------------------------------
📊 Análise da Etapa: 02_STAGING (Sem Duplicatas)
----------------------------------------
Total de linhas reais do dataset : 143623
Total de chaves primárias únicas : 143622

⚠️ ERRO PROVÁVEL: DUPLICAÇÃO DE LINHA ENCONTRADA!
Total de linhas 100% duplicadas: 0

⚠️ ERRO PROVÁVEL: LINHA COMPLETAMENTE VAZIA:
Total de linhas após remover vazias: 143622

[ VISUALIZAÇÃO DO DATASET - 02_STAGING (Sem Duplicatas) ]

,Ano,Semestre,Nome Mantenedora,Código e-MEC da Mantenedora,CNPJ da mantenedora,Nome da IES,Código e-MEC da IES,Organização Acadêmica da IES,UF da IES,Município da IES,Nome do Local de oferta,Código do Local de Oferta,Município do Local de Oferta,UF do Local de Oferta,Nome da Microrregião,Código da Microrregião,Código da Mesorregião,Nome da Mesorregião,Área do conhecimento,Subárea do conhecimento,Código do Grupo de Preferência,Nota de Corte Grupo Preferência,Código do Curso,Nome do Curso,Turno,Grau,Conceito,Vagas autorizadas e-mec,Vagas ofertadas FIES,Vagas além da Oferta,Vagas ocupadas,Valor bruto do curso,1 Semestre Bruto,2 Semestre Bruto,3 Semestre Bruto,4 Semestre Bruto,5 Semestre Bruto,6 Semestre Bruto,7 Semestre Bruto,8 Semestre Bruto,9 Semestre Bruto,10 Semestre Bruto,11 Semestre Bruto,12 Semestre Bruto,Valor do curso para o FIES,Índice de correção - IPCA,1 Semestre FIES,2 Semestre FIES,3 Semestre FIES,4 Semestre FIES,5 Semestre FIES,6 Semestre FIES,7 Semestre FIES,8 Semestre FIES,9 Semestre FIES,10 Semestre FIES,11 Semestre FIES,12 Semestre FIES,Participa do P-FIES,Vagas Ofertadas P-FIES,BANCO NORDESTE BRASIL (004),ITAU UNIBANCO (PRAVALER)(341),BV FINANCEIRA (PRAVALER)(455),BANCO ANDBANK (PRAVALER)(65),BANCO DA AMAZONIA S.A. (003),Valor do curso para FIES,Índice de correção - IPCA
0,2021.0,1.0,INSTITUTO LEAO SAMPAIO DE ENSINO UNIVERSITARIO...,1149.0,2.391959e+12,CENTRO UNIVERSITÃRIO DOUTOR LEÃ¿O SAMPAIO,1735.0,CENTRO UNIVERSITÁRIO,CE,JUAZEIRO DO NORTE,UNIDADE SAÃDE,4201.0,JUAZEIRO DO NORTE,CE,CARIRI,23032.0,2307.0,SUL CEARENSE,DIVERSAS ÁREAS,"CIÊNCIAS BIOLÓGICAS (BEL), BIOMEDICINA, BIOTEC...",118659.0,491.94,90434.0,BIOMEDICINA,NOTURNO,BACHARELADO,4,50.0,20.0,20.0,9.0,88139.64,9499.38,10863.30,10863.24,10863.24,10863.18,10863.12,12091.26,12232.92,NaN,NaN,NaN,NaN,77721.54,NaN,8376.55,9579.26,9579.21,9579.21,9579.15,9579.1,10662.07,10786.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021.0,1.0,UPPRIMORE SISTEMA EDUCACIONAL LTDA,17399.0,3.089193e+13,FACULDADE EDUCAMAIS,4995.0,FACULDADE,SP,SÃO PAULO,UNIDADE SEDE,659982.0,SÃO PAULO,SP,SÃO PAULO,35061.0,3515.0,METROPOLITANA DE SÃO PAULO,DIVERSAS ÁREAS,"CIÊNCIAS SOCIAIS, POLÍTICAS, ECONÔMICAS E CONT...",120993.0,590.16,115716.0,CIÊNCIAS CONTÁBEIS,NOTURNO,BACHARELADO,3,160.0,40.0,100.0,0.0,39960.00,4500.00,4500.00,4815.00,4815.00,5152.00,5152.00,5513.00,5513.00,NaN,NaN,NaN,NaN,39960.00,NaN,4500.00,4500.00,4815.00,4815.00,5152.00,5152.0,5513.00,5513.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021.0,1.0,SOCIEDADE EDUCACIONAL CESAR VIEIRA DINIZ - PET...,16313.0,2.088087e+13,FACULDADE DO VALE DO SÃO FRANCISCO,19674.0,FACULDADE,PE,PETROLINA,CAMPUS PRINCIPAL,1070116.0,PETROLINA,PE,PETROLINA,26005.0,2602.0,SÃO FRANCISCO PERNAMBUCANO,DIVERSAS ÁREAS,"ADMINISTRAÇÃO, ADMINISTRAÇÃO PÚBLICA, GESTÃO, ...",118899.0,529.46,1304648.0,ADMINISTRAÇÃO,NOTURNO,BACHARELADO,4,100.0,40.0,22.0,0.0,41760.00,5220.00,5220.00,5220.00,5220.00,5220.00,5220.00,5220.00,5220.00,NaN,NaN,NaN,NaN,41760.00,NaN,5220.00,5220.00,5220.00,5220.00,5220.00,5220.0,5220.00,5220.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021.0,1.0,"IREP SOCIEDADE DE ENSINO SUPERIOR, MEDIO E FUN...",545.0,2.608755e+12,FACULDADE ESTÁCIO DE ALAGOAS - ESTÁCIO FAL,1298.0,FACULDADE,AL,MACEIÓ,UNIDADE JATIÚCA,1006627.0,MACEIÓ,AL,MACEIÓ,27011.0,2703.0,LESTE ALAGOANO,DIVERSAS ÁREAS,"ADMINISTRAÇÃO, ADMINISTRAÇÃO PÚBLICA, GESTÃO, ...",119104.0,505.96,19848.0,ADMINISTRAÇÃO,MATUTINO,BACHARELADO,3,50.0,15.0,35.0,0.0,32907.44,4113.43,4113.43,4113.43,4113.43,4113.43,4113.43,4113.43,4113.43,NaN,NaN,NaN,NaN,23035.20,NaN,2879.40,2879.40,2879.40,2879.40,2879.40,2879.4,2879.40,2879.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021.0,1.0,SERVICOS EDUCACIONAIS DO LITORAL PAULISTA LTDA.,1247.0,3.931429e+12,FACULDADE DO LITORAL SUL PAULISTA,1898.0,FACULDADE,SP,PRAIA GRANDE,CANTO DO FORTE,658856.0,PRAIA GRANDE,SP,SANTOS,35063.0,3515.0,METROPOLITANA DE SÃO PAULO,"CURSOS DA ÁREA DE LICENCIATURA, PEDAGOGIA E NO...",PEDAGOGIA,120964.0,549.28,101747.0,PEDAGOGIA,NOTURNO,LICENCIATURA,4,150.0,10.0,0.0,0.0,42000.00,6000.00,6000.00,6000.00,6000.00,6000.00,6000.00,6000.00,NaN,NaN,NaN,NaN,NaN,39900.00,NaN,5700.00,5700.00,5700.00,5700.00,5700.00,5700.0,5700.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[ ESTATÍSTICAS DESCRITIVAS - 02_STAGING (Sem Duplicatas) ]

,Ano,Semestre,Código e-MEC da Mantenedora,CNPJ da mantenedora,Código e-MEC da IES,Código do Local de Oferta,Código da Microrregião,Código da Mesorregião,Código do Grupo de Preferência,Nota de Corte Grupo Preferência,Código do Curso,Vagas autorizadas e-mec,Vagas ofertadas FIES,Vagas além da Oferta,Vagas ocupadas,Valor bruto do curso,1 Semestre Bruto,2 Semestre Bruto,3 Semestre Bruto,4 Semestre Bruto,5 Semestre Bruto,6 Semestre Bruto,7 Semestre Bruto,8 Semestre Bruto,9 Semestre Bruto,10 Semestre Bruto,11 Semestre Bruto,12 Semestre Bruto,Valor do curso para o FIES,Índice de correção - IPCA,1 Semestre FIES,2 Semestre FIES,3 Semestre FIES,4 Semestre FIES,5 Semestre FIES,6 Semestre FIES,7 Semestre FIES,8 Semestre FIES,9 Semestre FIES,10 Semestre FIES,11 Semestre FIES,12 Semestre FIES,Vagas Ofertadas P-FIES,Valor do curso para FIES,Índice de correção - IPCA
count,143622.000000,143622.000000,143622.000000,1.436220e+05,143622.000000,1.436220e+05,143622.000000,143622.000000,143622.000000,140108.000000,1.436220e+05,143622.000000,143622.000000,143622.000000,143622.000000,1.436220e+05,143622.000000,143622.000000,143567.000000,143528.000000,127380.000000,121957.000000,113450.000000,111865.000000,61833.000000,60815.000000,893.000000,839.000000,68739.000000,0.0,143622.000000,143622.000000,143567.000000,143528.000000,127380.000000,121957.000000,113450.000000,111865.000000,61833.000000,60815.000000,893.000000,839.000000,74883.000000,74883.000000,0.0
mean,2019.976097,1.468835,4117.333598,2.258301e+13,3329.146489,6.681872e+05,32678.772967,3271.718588,80339.201425,549.550459,7.919362e+05,102.291982,30.803526,26.403441,1.177981,6.612514e+04,7277.378655,7290.774356,7473.315932,7563.763777,8021.517476,8165.216747,8514.022743,8570.619226,10058.350023,9996.297481,41429.330929,43450.300691,57674.315287,NaN,5965.105752,6020.501095,6208.825488,6322.964230,6759.537973,6924.789568,7287.575220,7394.049500,8754.699421,8705.210149,39658.978511,41617.819297,12.620114,54176.539371,NaN
std,0.821468,0.499030,6035.411385,2.453032e+13,5080.608306,3.813419e+05,9340.675469,934.461208,32596.159314,52.238235,8.207751e+05,76.143097,27.581152,38.965285,3.272158,5.427840e+04,4542.695581,4581.649879,4606.812246,4812.153865,4805.451857,5236.582705,5014.246998,5675.333607,5899.546205,5921.507218,20711.784361,20072.111855,53454.081636,NaN,4362.604366,4366.921752,4376.454474,4413.019266,4540.722918,4605.880395,4745.654816,4793.296598,5698.019882,5744.115250,19733.211722,19138.944793,23.496674,48350.346078,NaN
min,2019.000000,1.000000,10.000000,5.985700e+10,10.000000,2.240000e+02,11001.000000,1101.000000,42583.000000,450.000000,8.490000e+02,2.000000,1.000000,0.000000,0.000000,2.666640e+03,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,590.500000,590.500000,2985.000000,2985.000000,1737.960000,NaN,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,600.000000,600.000000,2238.750000,2238.750000,0.000000,2404.000000,NaN
25%,2019.000000,1.000000,418.000000,4.310392e+12,466.000000,6.578390e+05,28011.000000,2803.000000,49164.000000,514.440000,7.409600e+04,55.000000,15.000000,0.000000,0.000000,3.480000e+04,4811.000000,4809.270000,4896.000000,4993.320000,5464.430000,5605.320000,5880.165000,5918.280000,7140.000000,7104.000000,18786.000000,37774.420000,28658.330000,NaN,3594.020000,3619.200000,3844.990000,3929.310000,4374.000000,4524.770000,4825.512500,4881.980000,6114.000000,6030.600000,18786.000000,35544.315000,0.000000,26973.995000,NaN
50%,2020.000000,1.000000,1179.000000,9.099207e+12,1519.000000,6.592890e+05,33018.000000,3306.000000,60345.500000,554.300000,1.111849e+06,100.000000,25.000000,10.000000,0.000000,5.928480e+04,6606.000000,6611.330000,6770.570000,6857.160000,7250.930000,7382.000000,7653.960000,7686.000000,8802.000000,8726.520000,47940.000000,48766.680000,48912.000000,NaN,5159.110000,5188.010000,5406.000000,5537.730000,5983.970000,6159.150000,6534.000000,6632.620000,7714.920000,7671.270000,46485.420000,47321.280000,1.000000,46876.800000,NaN
75%,2021.000000,2.000000,2617.000000,3.469935e+13,3304.000000,1.049596e+06,35061.000000,3515.000000,120239.000000,583.240000,1.321981e+06,120.000000,40.000000,40.000000,1.000000,8.430000e+04,8571.000000,8590.080000,8896.060000,8995.500000,9453.900000,9553.860000,9882.000000,9900.000000,11394.000000,11250.000000,54875.120000,55675.620000,73900.050000,NaN,7188.000000,7242.000000,7437.960000,7610.760000,8028.000000,8184.000000,8610.000000,8760.000000,9822.000000,9733.870000,52890.000000,53400.000000,15.000000,70263.545000,NaN
max,2021.000000,2.000000,18055.000000,9.803985e+13,24550.000000,2.500004e+06,53001.000000,5301.000000,126809.000000,811.520000,5.001566e+06,4980.000000,1044.000000,1044.000000,218.000000,1.079105e+06,82872.000000,137265.000000,89343.200000,359400.000000,95722.020000,684214.000000,101026.500000,619800.000000,110314.140000,107259.970000,107259.970000,117985.960000,973892.470000,NaN,73200.000000,73200.000000,73200.000000,105975.000000,73200.000000,80001.750000,82865.000000,88001.930000,93960.000000,96802.120000,96802.120000,106482.330000,700.000000,895320.240000,NaN

⏳ Carregando dados da camada 03_TRANSFORM...

----------------------------------------
📊 Análise da Etapa: 03_TRANSFORM (Parquet Unificado)
----------------------------------------
Total de linhas reais do dataset : 143623
Total de chaves primárias únicas : 143622

⚠️ ERRO PROVÁVEL: DUPLICAÇÃO DE LINHA ENCONTRADA!
Total de linhas 100% duplicadas: 0

⚠️ ERRO PROVÁVEL: LINHA COMPLETAMENTE VAZIA:
Total de linhas após remover vazias: 143623

[ VISUALIZAÇÃO DO DATASET - 03_TRANSFORM (Parquet Unificado) ]

,ano_ofertas,semestre_ofertas,nome_mantenedora_ofertas,codigo_e_mec_mantenedora_ofertas,cnpj_mantenedora_ofertas,nome_ies_ofertas,codigo_e_mec_ies_ofertas,organizacao_academica_ies_ofertas,uf_ies_ofertas,municipio_ies_ofertas,nome_local_oferta_ofertas,codigo_local_oferta_ofertas,municipio_local_oferta_ofertas,uf_local_oferta_ofertas,nome_microrregiao_ofertas,codigo_microrregiao_ofertas,codigo_mesorregiao_ofertas,nome_mesorregiao_ofertas,area_conhecimento_ofertas,subarea_conhecimento_ofertas,codigo_grupo_preferencia_ofertas,nota_corte_grupo_preferencia_ofertas,codigo_curso_ofertas,nome_curso_ofertas,turno_ofertas,grau_ofertas,conceito_ofertas,vagas_autorizadas_e_mec_ofertas,vagas_ofertadas_fies_ofertas,vagas_alem_da_oferta_ofertas,vagas_ocupadas_ofertas,valor_bruto_curso_ofertas,semestre_1_bruto_ofertas,semestre_2_bruto_ofertas,semestre_3_bruto_ofertas,semestre_4_bruto_ofertas,semestre_5_bruto_ofertas,semestre_6_bruto_ofertas,semestre_7_bruto_ofertas,semestre_8_bruto_ofertas,semestre_9_bruto_ofertas,semestre_10_bruto_ofertas,semestre_11_bruto_ofertas,semestre_12_bruto_ofertas,valor_curso_fies_ofertas,indice_correcao_ipca_ofertas,semestre_1_fies_ofertas,semestre_2_fies_ofertas,semestre_3_fies_ofertas,semestre_4_fies_ofertas,semestre_5_fies_ofertas,semestre_6_fies_ofertas,semestre_7_fies_ofertas,semestre_8_fies_ofertas,semestre_9_fies_ofertas,semestre_10_fies_ofertas,semestre_11_fies_ofertas,semestre_12_fies_ofertas,participa_p_fies_ofertas,vagas_ofertadas_p_fies_ofertas,banco_nordeste_brasil_004_ofertas,itau_unibanco_pravaler_341_ofertas,bv_financeira_pravaler_455_ofertas,banco_andbank_pravaler_65_ofertas,banco_amazonia_sa_003_ofertas,NO_CURSO,CO_CURSO,CO_CINE_AREA_GERAL,NO_CINE_AREA_GERAL
0,2019.0,1.0,ANHANGUERA EDUCACIONAL PARTICIPACOES S/A,16452.0,4.310392e+12,FACULDADE ANHANGUERA DE ASSIS,21924.0,FACULDADE,SP,ASSIS,CAMPUS PRINCIPAL,1078477.0,ASSIS,SP,ASSIS,35039.0,3510.0,ASSIS,CURSOS DA ÁREA DE ENGENHARIA E CIÊNCIA DA COMP...,"ENGENHARIA DE PRODUÇÃO, DE MATERIAIS E CURSOS ...",45815.0,480.38,1367754.0,ENGENHARIA DE PRODUÇÃO,NOTURNO,BACHARELADO,4,50.0,20.0,30.0,0.0,84692.0,7985.0,8523.0,8523.0,8523.0,8523.0,8523.0,8523.0,8523.0,8523.0,8523.0,NaN,NaN,72467.0,NaN,5988.0,6392.0,6392.0,6392.0,6392.0,6819.0,8523.0,8523.0,8523.0,8523.0,NaN,NaN,NAO,0.0,N,N,N,N,N,ENGENHARIA DE PRODUÇÃO,1367754.0,7.0,"Engenharia, produção e construção"
1,2019.0,1.0,CV & C CONSULTORES ASSOCIADOS LTDA - EPP,12526.0,4.130323e+13,FACULDADE DE TECNOLOGIA ATENEU,13657.0,FACULDADE,CE,SÃO GONÇALO DO AMARANTE,UNIDADE SEDE,1042440.0,SÃO GONÇALO DO AMARANTE,CE,BAIXO CURU,23009.0,2302.0,NORTE CEARENSE,DIVERSAS ÁREAS,"DIREITO, COMÉRCIO EXTERIOR, BIBLIOTECONOMIA E ...",43323.0,558.26,1386597.0,DIREITO,NOTURNO,BACHARELADO,4,60.0,24.0,36.0,9.0,72600.0,7260.0,7260.0,7260.0,7260.0,7260.0,7260.0,7260.0,7260.0,7260.0,7260.0,NaN,NaN,68970.0,NaN,6897.0,6897.0,6897.0,6897.0,6897.0,6897.0,6897.0,6897.0,6897.0,6897.0,NaN,NaN,NAO,0.0,N,N,N,N,N,DIREITO,1386597.0,4.0,"Negócios, administração e direito"
2,2019.0,1.0,ANHANGUERA EDUCACIONAL PARTICIPACOES S/A,16452.0,4.310392e+12,FACULDADE ANHANGÜERA DE BAURU,5451.0,FACULDADE,SP,BAURU,UNIDADE SEDE,660075.0,BAURU,SP,BAURU,35020.0,3504.0,BAURU,CURSOS DA ÁREA DE ENGENHARIA E CIÊNCIA DA COMP...,"ENGENHARIA DE PRODUÇÃO, DE MATERIAIS E CURSOS ...",45493.0,540.62,1163753.0,ENGENHARIA DE PRODUÇÃO,MATUTINO,BACHARELADO,3,90.0,27.0,63.0,0.0,85066.0,8310.0,7457.0,17100.0,7457.0,7457.0,7457.0,7457.0,7457.0,7457.0,7457.0,NaN,NaN,71627.0,NaN,6233.0,5592.0,12825.0,5592.0,5592.0,5965.0,7457.0,7457.0,7457.0,7457.0,NaN,NaN,NAO,0.0,N,N,N,N,N,Engenharia De Produção,1163753.0,7.0,"Engenharia, produção e construção"
3,2019.0,1.0,EDITORA E DISTRIBUIDORA EDUCACIONAL S/A,14514.0,3.873365e+13,FACULDADE PITÁGORAS DO MARANHÃO,1452.0,FACULDADE,MA,SÃO LUÍS,CAMPUS - SÃO LUÍS - TURU,658496.0,SÃO LUÍS,MA,AGLOMERAÇÃO URBANA DE SÃO LUÍS,21002.0,2101.0,NORTE MARANHENSE,DIVERSAS ÁREAS,"ADMINISTRAÇÃO, ADMINISTRAÇÃO PÚBLICA, GESTÃO, ...",43074.0,539.50,21222.0,ADMINISTRAÇÃO,MATUTINO,BACHARELADO,3,48.0,14.0,34.0,0.0,42402.0,3984.0,4952.0,4812.0,5345.0,6408.0,3972.0,6948.0,5981.0,NaN,NaN,NaN,NaN,35232.0,NaN,2988.0,3714.0,3609.0,4009.0,4806.0,3177.0,6948.0,5981.0,NaN,NaN,NaN,NaN,NAO,0.0,N,N,N,N,N,Administração,21222.0,4.0,"Negócios, administração e direito"
4,2019.0,1.0,EDITORA E DISTRIBUIDORA EDUCACIONAL S/A,14514.0,3.873365e+13,FACULDADE PITÁGORAS DO MARANHÃO,1452.0,FACULDADE,MA,SÃO LUÍS,CAMPUS II,1076417.0,SÃO LUÍS,MA,AGLOMERAÇÃO URBANA DE SÃO LUÍS,21002.0,2101.0,NORTE MARANHENSE,CURSOS DA AREA DE SAUDE,"ENFERMAGEM, FISIOTERAPIA, FARMÁCIA, NUTRIÇÃO E...",43026.0,560.50,1104244.0,ENFERMAGEM,NOTURNO,BACHARELADO,4,90.0,36.0,54.0,0.0,91511.0,6795.0,7265.0,7662.0,8945.0,10404.0,8611.0,10938.0,9344.0,11880.0,9667.0,NaN,NaN,79522.0,NaN,5096.0,5449.0,5747.0,6709.0,7803.0,6889.0,10938.0,9344.0,11880.0,9667.0,NaN,NaN,NAO,0.0,N,N,N,N,N,Enfermagem,1104244.0,9.0,Saúde e bem-estar

[ ESTATÍSTICAS DESCRITIVAS - 03_TRANSFORM (Parquet Unificado) ]

,ano_ofertas,semestre_ofertas,codigo_e_mec_mantenedora_ofertas,cnpj_mantenedora_ofertas,codigo_e_mec_ies_ofertas,codigo_local_oferta_ofertas,codigo_microrregiao_ofertas,codigo_mesorregiao_ofertas,codigo_grupo_preferencia_ofertas,nota_corte_grupo_preferencia_ofertas,codigo_curso_ofertas,vagas_autorizadas_e_mec_ofertas,vagas_ofertadas_fies_ofertas,vagas_alem_da_oferta_ofertas,vagas_ocupadas_ofertas,valor_bruto_curso_ofertas,semestre_1_bruto_ofertas,semestre_2_bruto_ofertas,semestre_3_bruto_ofertas,semestre_4_bruto_ofertas,semestre_5_bruto_ofertas,semestre_6_bruto_ofertas,semestre_7_bruto_ofertas,semestre_8_bruto_ofertas,semestre_9_bruto_ofertas,semestre_10_bruto_ofertas,semestre_11_bruto_ofertas,semestre_12_bruto_ofertas,valor_curso_fies_ofertas,indice_correcao_ipca_ofertas,semestre_1_fies_ofertas,semestre_2_fies_ofertas,semestre_3_fies_ofertas,semestre_4_fies_ofertas,semestre_5_fies_ofertas,semestre_6_fies_ofertas,semestre_7_fies_ofertas,semestre_8_fies_ofertas,semestre_9_fies_ofertas,semestre_10_fies_ofertas,semestre_11_fies_ofertas,semestre_12_fies_ofertas,vagas_ofertadas_p_fies_ofertas,CO_CURSO,CO_CINE_AREA_GERAL
count,143622.000000,143622.000000,143622.000000,1.436220e+05,143622.000000,1.436220e+05,143622.000000,143622.000000,143622.000000,140108.000000,1.436220e+05,143622.000000,143622.000000,143622.000000,143622.000000,1.436220e+05,143622.000000,143622.000000,143567.000000,143528.000000,127380.000000,121957.000000,113450.000000,111865.000000,61833.000000,60815.000000,893.000000,839.000000,143622.000000,0.0,143622.000000,143622.000000,143567.000000,143528.000000,127380.000000,121957.000000,113450.000000,111865.000000,61833.000000,60815.000000,893.000000,839.000000,74883.000000,1.375030e+05,137503.000000
mean,2019.976097,1.468835,4117.333598,2.258301e+13,3329.146489,6.681872e+05,32678.772967,3271.718588,80339.201425,549.550459,7.919362e+05,102.291982,30.803526,26.403441,1.177981,6.612514e+04,7277.378655,7290.774356,7473.315932,7563.763777,8021.517476,8165.216747,8514.022743,8570.619226,10058.350023,9996.297481,41429.330929,43450.300691,55850.611718,NaN,5965.105752,6020.501095,6208.825488,6322.964230,6759.537973,6924.789568,7287.575220,7394.049500,8754.699421,8705.210149,39658.978511,41617.819297,12.620114,7.739179e+05,5.848665
std,0.821468,0.499030,6035.411385,2.453032e+13,5080.608306,3.813419e+05,9340.675469,934.461208,32596.159314,52.238235,8.207751e+05,76.143097,27.581152,38.965285,3.272158,5.427840e+04,4542.695581,4581.649879,4606.812246,4812.153865,4805.451857,5236.582705,5014.246998,5675.333607,5899.546205,5921.507218,20711.784361,20072.111855,50886.822127,NaN,4362.604366,4366.921752,4376.454474,4413.019266,4540.722918,4605.880395,4745.654816,4793.296598,5698.019882,5744.115250,19733.211722,19138.944793,23.496674,8.264984e+05,2.672486
min,2019.000000,1.000000,10.000000,5.985700e+10,10.000000,2.240000e+02,11001.000000,1101.000000,42583.000000,450.000000,8.490000e+02,2.000000,1.000000,0.000000,0.000000,2.666640e+03,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,590.500000,590.500000,2985.000000,2985.000000,1737.960000,NaN,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,459.630000,600.000000,600.000000,2238.750000,2238.750000,0.000000,8.490000e+02,1.000000
25%,2019.000000,1.000000,418.000000,4.310392e+12,466.000000,6.578390e+05,28011.000000,2803.000000,49164.000000,514.440000,7.409600e+04,55.000000,15.000000,0.000000,0.000000,3.480000e+04,4811.000000,4809.270000,4896.000000,4993.320000,5464.430000,5605.320000,5880.165000,5918.280000,7140.000000,7104.000000,18786.000000,37774.420000,27835.200000,NaN,3594.020000,3619.200000,3844.990000,3929.310000,4374.000000,4524.770000,4825.512500,4881.980000,6114.000000,6030.600000,18786.000000,35544.315000,0.000000,7.302500e+04,4.000000
50%,2020.000000,1.000000,1179.000000,9.099207e+12,1519.000000,6.592890e+05,33018.000000,3306.000000,60345.500000,554.300000,1.111849e+06,100.000000,25.000000,10.000000,0.000000,5.928480e+04,6606.000000,6611.330000,6770.570000,6857.160000,7250.930000,7382.000000,7653.960000,7686.000000,8802.000000,8726.520000,47940.000000,48766.680000,47765.690000,NaN,5159.110000,5188.010000,5406.000000,5537.730000,5983.970000,6159.150000,6534.000000,6632.620000,7714.920000,7671.270000,46485.420000,47321.280000,1.000000,1.099586e+06,6.000000
75%,2021.000000,2.000000,2617.000000,3.469935e+13,3304.000000,1.049596e+06,35061.000000,3515.000000,120239.000000,583.240000,1.321981e+06,120.000000,40.000000,40.000000,1.000000,8.430000e+04,8571.000000,8590.080000,8896.060000,8995.500000,9453.900000,9553.860000,9882.000000,9900.000000,11394.000000,11250.000000,54875.120000,55675.620000,71880.000000,NaN,7188.000000,7242.000000,7437.960000,7610.760000,8028.000000,8184.000000,8610.000000,8760.000000,9822.000000,9733.870000,52890.000000,53400.000000,15.000000,1.306246e+06,9.000000
max,2021.000000,2.000000,18055.000000,9.803985e+13,24550.000000,2.500004e+06,53001.000000,5301.000000,126809.000000,811.520000,5.001566e+06,4980.000000,1044.000000,1044.000000,218.000000,1.079105e+06,82872.000000,137265.000000,89343.200000,359400.000000,95722.020000,684214.000000,101026.500000,619800.000000,110314.140000,107259.970000,107259.970000,117985.960000,973892.470000,NaN,73200.000000,73200.000000,73200.000000,105975.000000,73200.000000,80001.750000,82865.000000,88001.930000,93960.000000,96802.120000,96802.120000,106482.330000,700.000000,5.001535e+06,10.000000

==================================================
✅ VALIDAÇÃO DE QUALIDADE CONCLUÍDA
==================================================