In [ ]:
#analise_001 trata-se apenas de criaca do dataset load de inscritos
#  mas apenas inscritos dado prioridade inicial
#  e outro dataset tbm mas com apenas certas colunas

import pandas as pd
import os
from constantes import pasta_data_04_load_inscritos, pasta_data_04_load_ofertas, pasta_data_05_processed

pd.set_option('display.max_columns', None)#type: ignore
pd.set_option('display.max_rows', None) #type: ignore

# ==========================================
# 1. CARREGAMENTO DOS DADOS E CAMINHOS
# ==========================================
path = str(pasta_data_04_load_inscritos)
df = pd.read_parquet(path)

path_save = str(pasta_data_05_processed)
nome = os.path.join(path_save, 'candidatos_unicos_por_prioridade_inicial.parquet')
nome_agregado = os.path.join(path_save, 'candidatos_unicos_por_prioridade_inicial_por_cine_e_regiao_moradia.parquet')

# ==========================================
# 2. REGRAS DE NEGÓCIO (FUNIL DE PRIORIDADE)
# ==========================================
ordem_de_prioridade = [
    'CONTRATADA',                            # 1. Ganhou a vaga.
    'INSCRIÇÃO POSTERGADA',                  # 2. Ganhou a vaga pro semestre que vem.
    'PRÉ-SELECIONADO',                       # 3. Está vivo no processo agora mesmo! Ainda não enviou os docs.
    'NÃO CONTRATADO',                        # 4. Chegou no banco, mas falhou, ou não enviou docs à CPSA.
    'REJEITADA PELA CPSA',                   # 5. Chegou na faculdade, mas a documentação falhou.
    'OPÇÃO NÃO CONTRATADA',                  # 6. Status de sistema (a outra opção dele deu certo).
    'PARTICIPACAO CANCELADA PELO CANDIDATO', # 7. Desistência voluntária.
    'LISTA DE ESPERA'                        # 8. Nunca passou na nota, o menor progresso possível.
]

chave_agrupamento_inscritos = [
    'ano',
    'semestre',
    'regiao_morar',
    #'regiao_ies_alvo',
    'nome_cine_area_geral',
    "uf_local_oferta",
    'situacao_fies',
]

# A prioridade ('situacao_fies') vem antes da 'opcao_curso' para garantir o melhor status no desempate
ordem_sort_opcao_em_ultimo = [
    'ano',
    'semestre',
    'id_estudante',
    'situacao_fies',
    'opcao_curso',
]

subset_drop = [
    'ano',
    'semestre',
    'id_estudante'
]

# ==========================================
# 3. PROCESSAMENTO E EXTRAÇÃO DE ÚNICOS
# ==========================================
df_convertido = df.copy()

# Tipagem categórica para aplicar a ordem customizada
df_convertido['situacao_fies'] = pd.Categorical(
    df_convertido['situacao_fies'],
    categories=ordem_de_prioridade,
    ordered=True
)

# Ordenação
df_situacaoInscricaoOrdenadaPorPrioridades = (df_convertido
                                            .sort_values(
                                            by=ordem_sort_opcao_em_ultimo,
                                            ascending=True))

# Remoção de duplicatas (Candidato Único por Semestre/Ano mantendo a melhor situação)
df_candidatos_unicos = (df_situacaoInscricaoOrdenadaPorPrioridades
                      .drop_duplicates(subset=subset_drop, keep='first'))

# ==========================================
# 4. AGRUPAMENTO BASE (O DATASET AGREGADO)
# ==========================================
# O parâmetro dropna=False garante que os 11 alunos com região "NaN" sejam contados!
df_candidatos_unicos_agrupados = (df_candidatos_unicos
                                  .groupby(chave_agrupamento_inscritos, as_index=False, observed=True, dropna=True)['id_estudante']
                                  .count())

                                  #dropna=False no gorupby para que SE uamdas coluans de CHAVE AGRUPAMENTO for false, ele NAO deleta, entao TRUE...

# Renomeia a coluna para um nome simples e direto e ordena a tabela
nome_coluna_qtde = 'qtde_candidatos'
df_candidatos_unicos_agrupados = (df_candidatos_unicos_agrupados
                                  .rename(columns={'id_estudante': nome_coluna_qtde})
                                  .sort_values(['ano', 'semestre', 'uf_local_oferta']))

# ==========================================
# 5. EXIBIÇÃO DOS RESULTADOS (DISPLAYS)#type: ignore
# ==========================================

print('--- 1. QTDE TOTAL DE CANDIDATOS ÚNICOS DE 2019-1 ATÉ 2021-2 ---')
qtde_total = df_candidatos_unicos_agrupados[nome_coluna_qtde].sum()
display(qtde_total) #type: ignore
print('\n')


print('--- 2. QTDE DE CANDIDATOS POR ÁREA CINE ---')
# Agrupa apenas por Área CINE e soma a quantidade de candidatos
df_qtde_area_cine = (df_candidatos_unicos_agrupados
                     .groupby('nome_cine_area_geral', as_index=False)[[nome_coluna_qtde]]
                     .sum()
                     .sort_values(by=nome_coluna_qtde, ascending=False))

# Renomeia a coluna especificamente para esta visão ficar clara
df_qtde_area_cine = df_qtde_area_cine.rename(columns={nome_coluna_qtde: 'qtde_candidatos_por_area_cine'})
display(df_qtde_area_cine.head(50)) #type: ignore
print('\n')


print('--- 3. QTDE DE CANDIDATOS UNICOS EM CADA SITUACAO FIES, DE MESMA REGIAO, POR AREA CINE EM CADA UF DA IES ALVO, POR ANO/SEMESTRE ---')
# Mostra a base agregada que contém Ano, Semestre, Área, UF, Situação e Qtde
display(df_candidatos_unicos_agrupados.head(50)) #type: ignore
print('\n')


print('--- 4. QTDE DE CANDIDATOS POR ANO E SITUAÇÃO DO FIES ---')
# Usa observed=True para não gerar FutureWarning e .sum() para somar os alunos reais
df_situacao_ano = (df_candidatos_unicos_agrupados
                   .groupby(['ano', 'situacao_fies'], observed=True)
                   .agg(qtde_candidatos=(nome_coluna_qtde, 'sum'))
                   .reset_index()
                   .sort_values(by=['ano', 'qtde_candidatos'], ascending=[True, False]))

display(df_situacao_ano) #type: ignore
print('\n')






print('--- 5. QTDE DE CANDIDATOS QUE RESIDEM NA MESMA REGIAO, POR ÁREA CINE ---')

# Agrupa pela Área CINE e pela Região que JÁ EXISTE e sobreviveu no df agregado
df_qtde_area_regiao = (df_candidatos_unicos_agrupados
                       .groupby(['nome_cine_area_geral', 'regiao_morar'], as_index=False)[[nome_coluna_qtde]]
                       .sum()
                       .sort_values(by=['nome_cine_area_geral', nome_coluna_qtde], ascending=[True, False]))

# Renomeia para fazer sentido com ESTE display
df_qtde_area_regiao = df_qtde_area_regiao.rename(columns={nome_coluna_qtde: 'qtde_candidatos_por_area_cine_e_regiao'})

# Exibe os resultados
display(df_qtde_area_regiao.head(50)) #type: ignore
print('\n')



print('--- 6. QTDE DE CANDIDATOS QUE RESIDEM NA MESMA REGIAO, POR ÁREA CINE POR ANO e SEMESTRE ---')

# Agrupa pela Área CINE e pela Região que JÁ EXISTE e sobreviveu no df agregado
df_qtde_area_regiao_ano_e_semestre = (df_candidatos_unicos_agrupados
                       .groupby(['nome_cine_area_geral', 'regiao_morar','ano','semestre'], as_index=False)[[nome_coluna_qtde]]
                       .sum()
                       .sort_values(by=['ano','semestre', nome_coluna_qtde], ascending=True))

# Renomeia para fazer sentido com ESTE display
df_qtde_area_regiao_ano_e_semestre = df_qtde_area_regiao_ano_e_semestre.rename(columns={nome_coluna_qtde: 'qtde_candidatos_por_area_cine_e_regiao_ano_e_semestre '})

# Exibe os resultados
display(df_qtde_area_regiao_ano_e_semestre.head(50)) #type: ignore
print('\n')


print('salvando os 2 dataset, inscritos normais porem somente inscritos que sao candidatos unicos e o apenas com colunas de interesse (display 3)')
df_candidatos_unicos.to_parquet(nome,index=False)

df_candidatos_unicos_agrupados.to_parquet(nome_agregado,index=False)

print('SALVO')

--- 1. QTDE TOTAL DE CANDIDATOS ÚNICOS DE 2019-1 ATÉ 2021-2 ---

np.int64(1109882)

--- 2. QTDE DE CANDIDATOS POR ÁREA CINE ---

,nome_cine_area_geral,qtde_candidatos_por_area_cine
8,Saúde e bem-estar,556104
7,"Negócios, administração e direito",245488
6,"Engenharia, produção e construção",92531
3,"Ciências sociais, comunicação e informação",77995
0,"Agricultura, silvicultura, pesca e veterinária",48062
5,Educação,33944
4,Computação e Tecnologias da Informação e Comun...,25503
9,Serviços,16407
1,Artes e humanidades,10412
2,"Ciências naturais, matemática e estatística",3436

--- 3. QTDE DE CANDIDATOS UNICOS EM CADA SITUACAO FIES, DE MESMA REGIAO, POR AREA CINE EM CADA UF DA IES ALVO, POR ANO/SEMESTRE ---

,ano,semestre,regiao_morar,nome_cine_area_geral,uf_local_oferta,situacao_fies,qtde_candidatos
244,2019,1,Centro-Oeste,Saúde e bem-estar,AC,NÃO CONTRATADO,1
479,2019,1,Nordeste,"Ciências sociais, comunicação e informação",AC,NÃO CONTRATADO,1
830,2019,1,Nordeste,Saúde e bem-estar,AC,NÃO CONTRATADO,3
831,2019,1,Nordeste,Saúde e bem-estar,AC,PARTICIPACAO CANCELADA PELO CANDIDATO,1
1081,2019,1,Norte,"Ciências sociais, comunicação e informação",AC,CONTRATADA,11
1082,2019,1,Norte,"Ciências sociais, comunicação e informação",AC,NÃO CONTRATADO,66
1083,2019,1,Norte,"Ciências sociais, comunicação e informação",AC,PARTICIPACAO CANCELADA PELO CANDIDATO,6
1084,2019,1,Norte,"Ciências sociais, comunicação e informação",AC,LISTA DE ESPERA,17
1142,2019,1,Norte,Computação e Tecnologias da Informação e Comun...,AC,CONTRATADA,12
1143,2019,1,Norte,Computação e Tecnologias da Informação e Comun...,AC,NÃO CONTRATADO,35
1175,2019,1,Norte,Educação,AC,CONTRATADA,6
1176,2019,1,Norte,Educação,AC,NÃO CONTRATADO,49
1177,2019,1,Norte,Educação,AC,PARTICIPACAO CANCELADA PELO CANDIDATO,3
1178,2019,1,Norte,Educação,AC,LISTA DE ESPERA,22
1220,2019,1,Norte,"Engenharia, produção e construção",AC,CONTRATADA,37
1221,2019,1,Norte,"Engenharia, produção e construção",AC,NÃO CONTRATADO,74
1222,2019,1,Norte,"Engenharia, produção e construção",AC,PARTICIPACAO CANCELADA PELO CANDIDATO,2
1223,2019,1,Norte,"Engenharia, produção e construção",AC,LISTA DE ESPERA,58
1285,2019,1,Norte,"Negócios, administração e direito",AC,CONTRATADA,54
1286,2019,1,Norte,"Negócios, administração e direito",AC,NÃO CONTRATADO,205
1287,2019,1,Norte,"Negócios, administração e direito",AC,PARTICIPACAO CANCELADA PELO CANDIDATO,9
1288,2019,1,Norte,"Negócios, administração e direito",AC,LISTA DE ESPERA,377
1361,2019,1,Norte,Saúde e bem-estar,AC,CONTRATADA,186
1362,2019,1,Norte,Saúde e bem-estar,AC,NÃO CONTRATADO,354
1363,2019,1,Norte,Saúde e bem-estar,AC,PARTICIPACAO CANCELADA PELO CANDIDATO,16
1364,2019,1,Norte,Saúde e bem-estar,AC,LISTA DE ESPERA,212
1461,2019,1,Norte,Serviços,AC,CONTRATADA,17
1462,2019,1,Norte,Serviços,AC,NÃO CONTRATADO,24
1802,2019,1,Sudeste,Saúde e bem-estar,AC,NÃO CONTRATADO,1
245,2019,1,Centro-Oeste,Saúde e bem-estar,AL,CONTRATADA,1
246,2019,1,Centro-Oeste,Saúde e bem-estar,AL,NÃO CONTRATADO,1
247,2019,1,Centro-Oeste,Saúde e bem-estar,AL,PARTICIPACAO CANCELADA PELO CANDIDATO,2
248,2019,1,Centro-Oeste,Saúde e bem-estar,AL,LISTA DE ESPERA,16
351,2019,1,Nordeste,"Agricultura, silvicultura, pesca e veterinária",AL,CONTRATADA,39
352,2019,1,Nordeste,"Agricultura, silvicultura, pesca e veterinária",AL,NÃO CONTRATADO,57
353,2019,1,Nordeste,"Agricultura, silvicultura, pesca e veterinária",AL,PARTICIPACAO CANCELADA PELO CANDIDATO,2
354,2019,1,Nordeste,"Agricultura, silvicultura, pesca e veterinária",AL,LISTA DE ESPERA,4
406,2019,1,Nordeste,Artes e humanidades,AL,CONTRATADA,4
407,2019,1,Nordeste,Artes e humanidades,AL,NÃO CONTRATADO,14
408,2019,1,Nordeste,Artes e humanidades,AL,OPÇÃO NÃO CONTRATADA,1
409,2019,1,Nordeste,Artes e humanidades,AL,PARTICIPACAO CANCELADA PELO CANDIDATO,2
410,2019,1,Nordeste,Artes e humanidades,AL,LISTA DE ESPERA,2
452,2019,1,Nordeste,"Ciências naturais, matemática e estatística",AL,CONTRATADA,1
453,2019,1,Nordeste,"Ciências naturais, matemática e estatística",AL,LISTA DE ESPERA,10
480,2019,1,Nordeste,"Ciências sociais, comunicação e informação",AL,CONTRATADA,56
481,2019,1,Nordeste,"Ciências sociais, comunicação e informação",AL,NÃO CONTRATADO,232
482,2019,1,Nordeste,"Ciências sociais, comunicação e informação",AL,PARTICIPACAO CANCELADA PELO CANDIDATO,12
483,2019,1,Nordeste,"Ciências sociais, comunicação e informação",AL,LISTA DE ESPERA,20
550,2019,1,Nordeste,Computação e Tecnologias da Informação e Comun...,AL,CONTRATADA,5
551,2019,1,Nordeste,Computação e Tecnologias da Informação e Comun...,AL,NÃO CONTRATADO,57

--- 4. QTDE DE CANDIDATOS POR ANO E SITUAÇÃO DO FIES ---

     ano                          situacao_fies  qtde_candidatos
3   2019                         NÃO CONTRATADO           219931
7   2019                        LISTA DE ESPERA           176492
0   2019                             CONTRATADA            72210
6   2019  PARTICIPACAO CANCELADA PELO CANDIDATO            15153
5   2019                   OPÇÃO NÃO CONTRATADA              902
4   2019                    REJEITADA PELA CPSA              774
2   2019                        PRÉ-SELECIONADO               79
1   2019                   INSCRIÇÃO POSTERGADA               17
15  2020                        LISTA DE ESPERA           157799
11  2020                         NÃO CONTRATADO           150758
8   2020                             CONTRATADA            46207
14  2020  PARTICIPACAO CANCELADA PELO CANDIDATO            20754
12  2020                    REJEITADA PELA CPSA              868
13  2020                   OPÇÃO NÃO CONTRATADA              610
10  2020                        PRÉ-SELECIONADO               84
9   2020                   INSCRIÇÃO POSTERGADA               27
19  2021                         NÃO CONTRATADO           108095
23  2021                        LISTA DE ESPERA            69357
16  2021                             CONTRATADA            41949
22  2021  PARTICIPACAO CANCELADA PELO CANDIDATO            18649
18  2021                        PRÉ-SELECIONADO             6315
20  2021                    REJEITADA PELA CPSA             1346
17  2021                   INSCRIÇÃO POSTERGADA             1202
21  2021                   OPÇÃO NÃO CONTRATADA              304

--- 5. QTDE DE CANDIDATOS QUE RESIDEM NA MESMA REGIAO, POR ÁREA CINE ---

,nome_cine_area_geral,regiao_morar,qtde_candidatos_por_area_cine_e_regiao
3,"Agricultura, silvicultura, pesca e veterinária",Sudeste,20394
1,"Agricultura, silvicultura, pesca e veterinária",Nordeste,10571
4,"Agricultura, silvicultura, pesca e veterinária",Sul,7206
0,"Agricultura, silvicultura, pesca e veterinária",Centro-Oeste,5467
2,"Agricultura, silvicultura, pesca e veterinária",Norte,4424
8,Artes e humanidades,Sudeste,4991
6,Artes e humanidades,Nordeste,2954
9,Artes e humanidades,Sul,1032
5,Artes e humanidades,Centro-Oeste,734
7,Artes e humanidades,Norte,701
13,"Ciências naturais, matemática e estatística",Sudeste,2127
11,"Ciências naturais, matemática e estatística",Nordeste,467
10,"Ciências naturais, matemática e estatística",Centro-Oeste,410
14,"Ciências naturais, matemática e estatística",Sul,244
12,"Ciências naturais, matemática e estatística",Norte,188
18,"Ciências sociais, comunicação e informação",Sudeste,29851
16,"Ciências sociais, comunicação e informação",Nordeste,26097
19,"Ciências sociais, comunicação e informação",Sul,8124
17,"Ciências sociais, comunicação e informação",Norte,7135
15,"Ciências sociais, comunicação e informação",Centro-Oeste,6788
23,Computação e Tecnologias da Informação e Comun...,Sudeste,10021
21,Computação e Tecnologias da Informação e Comun...,Nordeste,7722
22,Computação e Tecnologias da Informação e Comun...,Norte,2962
20,Computação e Tecnologias da Informação e Comun...,Centro-Oeste,2482
24,Computação e Tecnologias da Informação e Comun...,Sul,2316
28,Educação,Sudeste,12104
26,Educação,Nordeste,10509
27,Educação,Norte,5885
25,Educação,Centro-Oeste,3101
29,Educação,Sul,2345
33,"Engenharia, produção e construção",Sudeste,36470
31,"Engenharia, produção e construção",Nordeste,28546
32,"Engenharia, produção e construção",Norte,10802
34,"Engenharia, produção e construção",Sul,10162
30,"Engenharia, produção e construção",Centro-Oeste,6551
36,"Negócios, administração e direito",Nordeste,84899
38,"Negócios, administração e direito",Sudeste,83243
37,"Negócios, administração e direito",Norte,33368
39,"Negócios, administração e direito",Sul,22954
35,"Negócios, administração e direito",Centro-Oeste,21024
41,Saúde e bem-estar,Nordeste,205361
43,Saúde e bem-estar,Sudeste,194587
42,Saúde e bem-estar,Norte,60442
40,Saúde e bem-estar,Centro-Oeste,50413
44,Saúde e bem-estar,Sul,45301
46,Serviços,Nordeste,6164
48,Serviços,Sudeste,5367
47,Serviços,Norte,2084
45,Serviços,Centro-Oeste,1458
49,Serviços,Sul,1334

--- 6. QTDE DE CANDIDATOS QUE RESIDEM NA MESMA REGIAO, POR ÁREA CINE POR ANO e SEMESTRE ---

,nome_cine_area_geral,regiao_morar,ano,semestre,qtde_candidatos_por_area_cine_e_regiao_ano_e_semestre
72,"Ciências naturais, matemática e estatística",Norte,2019,1,86
84,"Ciências naturais, matemática e estatística",Sul,2019,1,100
60,"Ciências naturais, matemática e estatística",Centro-Oeste,2019,1,158
42,Artes e humanidades,Norte,2019,1,251
66,"Ciências naturais, matemática e estatística",Nordeste,2019,1,266
30,Artes e humanidades,Centro-Oeste,2019,1,286
54,Artes e humanidades,Sul,2019,1,379
294,Serviços,Sul,2019,1,477
270,Serviços,Centro-Oeste,2019,1,530
282,Serviços,Norte,2019,1,678
144,Computação e Tecnologias da Informação e Comun...,Sul,2019,1,820
78,"Ciências naturais, matemática e estatística",Sudeste,2019,1,836
120,Computação e Tecnologias da Informação e Comun...,Centro-Oeste,2019,1,922
132,Computação e Tecnologias da Informação e Comun...,Norte,2019,1,992
174,Educação,Sul,2019,1,1065
36,Artes e humanidades,Nordeste,2019,1,1101
12,"Agricultura, silvicultura, pesca e veterinária",Norte,2019,1,1306
150,Educação,Centro-Oeste,2019,1,1371
0,"Agricultura, silvicultura, pesca e veterinária",Centro-Oeste,2019,1,1611
48,Artes e humanidades,Sudeste,2019,1,1794
102,"Ciências sociais, comunicação e informação",Norte,2019,1,2092
276,Serviços,Nordeste,2019,1,2102
288,Serviços,Sudeste,2019,1,2119
90,"Ciências sociais, comunicação e informação",Centro-Oeste,2019,1,2150
24,"Agricultura, silvicultura, pesca e veterinária",Sul,2019,1,2186
162,Educação,Norte,2019,1,2357
114,"Ciências sociais, comunicação e informação",Sul,2019,1,2481
180,"Engenharia, produção e construção",Centro-Oeste,2019,1,2558
126,Computação e Tecnologias da Informação e Comun...,Nordeste,2019,1,2678
6,"Agricultura, silvicultura, pesca e veterinária",Nordeste,2019,1,2701
138,Computação e Tecnologias da Informação e Comun...,Sudeste,2019,1,3633
192,"Engenharia, produção e construção",Norte,2019,1,3919
204,"Engenharia, produção e construção",Sul,2019,1,3952
156,Educação,Nordeste,2019,1,4360
168,Educação,Sudeste,2019,1,5520
18,"Agricultura, silvicultura, pesca e veterinária",Sudeste,2019,1,6418
96,"Ciências sociais, comunicação e informação",Nordeste,2019,1,7536
210,"Negócios, administração e direito",Centro-Oeste,2019,1,7885
234,"Negócios, administração e direito",Sul,2019,1,8490
108,"Ciências sociais, comunicação e informação",Sudeste,2019,1,9793
186,"Engenharia, produção e construção",Nordeste,2019,1,10936
222,"Negócios, administração e direito",Norte,2019,1,10950
264,Saúde e bem-estar,Sul,2019,1,11807
240,Saúde e bem-estar,Centro-Oeste,2019,1,13625
198,"Engenharia, produção e construção",Sudeste,2019,1,14842
252,Saúde e bem-estar,Norte,2019,1,16278
216,"Negócios, administração e direito",Nordeste,2019,1,28457
228,"Negócios, administração e direito",Sudeste,2019,1,31333
258,Saúde e bem-estar,Sudeste,2019,1,52150
246,Saúde e bem-estar,Nordeste,2019,1,54881

salvando os 2 dataset, inscritos normais porem somente inscritos que sao candidatos unicos e o apenas com colunas de interesse (display 3)
SALVO